# nonk8s
# yaml-language-server: $schema=https://software.backbase.eu/schema.json#/definitions/InternalComponent
apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backbase-services-toolkit
  description: An IntelliJ Plugin to help you to create and maintain your own Backbase backend services. It would make it easier for you to follow Community Backbase Documentation.
  annotations:
    jira/maint-component: Backend DevKit
    jira/maint-subcomponent: Mock Services
    jira/project-key: BEFOUND
    slack/conversation-id: C037FUQMXF0
  tags:
    - intellij
    - ssdk
  links:
    - url: 'https://github.com/Backbase/backbase-services-toolkit/releases'
      title: Releases
      icon: dashboard
    - url: 'https://github.com/Backbase/backbase-services-toolkit/actions/workflows/build.yml'
      title: Github Action - Build
      icon: cloud
    - url: 'https://github.com/Backbase/backbase-services-toolkit/actions/workflows/release.yml'
      title: Github Action - Release
      icon: cloud
    - url: 'http://engineering.backbase.com/intellij-docs/'
      title: Documentation
      icon: dashboard
    - url: 'https://github.com/Backbase/intellij-docs'
      title: Documentation Repo
      icon: dashboard
    - url: 'https://plugins.jetbrains.com/plugin/18745-backbase-services-toolkit'
      title: Jetbrains Marketplace
      icon: dashboard
spec:
  type: internal
  lifecycle: experimental
  owner: DE - Backend Foundation
