package com.backbase.bst.actions.openapi

object SpecConstants {
    const val YAML = "YAML"
    const val POM_XML = "pom.xml"
    const val CLIENT_SERVICE_NAME_UPPERCASE = "CLIENT_SERVICE_NAME_UPPERCASE"
    const val CLIENT_SERVICE_NAME_LOWERCASE = "CLIENT_SERVICE_NAME_LOWERCASE"
    const val CLIENT_API_PACKAGE_TRIM_LAST_DOT = "CLIENT_API_PACKAGE_TRIM_LAST_DOT"
    const val CLIENT_SERVICE_NAME_CAMELCASE = "CLIENT_SERVICE_NAME_CAMELCASE"
    const val CLIENT_SERVICE_NAME_WITHOUT_SERVICE_CAMELCASE = "CLIENT_SERVICE_NAME_WITHOUT_SERVICE_CAMELCASE"
    const val CLIENT_SERVICE_NAME_SINGLE_WORD_WITHOUT_SERVICE_LOWERCASE = "CLIENT_SERVICE_NAME_SINGLE_WORD_WITHOUT_SERVICE_LOWERCASE"
}
